#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

			
def F(n):
    if n == 0: return 0
    elif n == 1: return 1
    else: return F(n-1)+F(n-2)
	
n=0
total=0
while F(n)<4000000: 
	if F(n)%2==0:
		total=total+F(n)
		n=n+1
		print(total)
	elif F(n)%2!=0:
		n=n+1
print(total)
